source 'https://rubygems.org'
ruby '2.1.0'
gem 'rails', '4.1.4'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0',          group: :doc
gem 'spring',        group: :development
gem 'high_voltage'
gem 'omniauth'
gem 'omniauth-facebook'
gem 'pg'

gem 'mecab-ruby', path: './local_gems/mecab-ruby-0.996'
gem "paranoia", "~> 2.0"
gem "active_model_serializers"
gem 'rack-cors', :require => 'rack/cors'

group :development do
  gem 'better_errors'
  gem 'binding_of_caller', :platforms=>[:mri_21]
  gem 'guard-bundler'
  gem 'guard-rails'
  gem 'guard-rspec'
  gem 'quiet_assets'
  gem 'rails_layout'
  gem 'rb-fchange', :require=>false
  gem 'rb-fsevent', :require=>false
  gem 'rb-inotify', :require=>false
end
group :development, :test do
  gem 'factory_girl_rails'
  gem 'rspec-rails'
end
group :test do
  gem 'capybara'
  gem 'database_cleaner'
  gem 'faker'
  gem 'launchy'
  gem 'selenium-webdriver'
end

group :development, :test do
  gem 'pry'
  gem 'awesome_print'
  gem 'hirb'
  gem 'pry-rails'
  gem 'pry-doc'
  gem 'pry-git'
  gem 'pry-remote'
  gem 'pry-debugger'
  gem 'pry-stack_explorer'
  gem 'coolline'
  gem 'coderay'
  gem 'pry-rescue'
  gem 'gnuplot'
  gem 'commands'
  gem 'rails-env-switcher'
  gem 'rspec-console'
end
