# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 47f09362140eb7154cb164cbd26329d0e968de282bd857ebf95a8472de4342515e0f65dbac4cdef53cb0ada34c8383887cc3d0994f850d74732dc26cf7febe30

test:
  secret_key_base: 91de49bb455668a3e1259268abdec94be37600a4ad1b9c9051217934382633c585a814d921c453256204b74e317968fbbac07eb0f289f3974763ae9f2a5b887d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
